---
name: olx_mobx
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  brasil_fields: ^0.6.0
  cached_network_image: ^2.4.1
  carousel_pro: ^1.0.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  mobx: ^1.2.1+3
  parse_server_sdk_flutter: ^2.0.1
  path: ^1.7.0
  readmore: ^1.0.1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  toggle_switch: ^0.1.8
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.1+1
flutter:
  uses-material-design: true
